name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Render
      run: |
        # Render deployment via webhook
        curl -X POST ${{ secrets.RENDER_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
